export const sampleUsers = [
  {
    id: "u-1",
    fullname: "Aarav Mehta",
    email: "aarav@acme.dev",
    role: "admin",
    status: "active",
    mobileNo: "+91 98765 43210",
    createdAt: "2026-05-08T09:00:00.000Z",
    designation: "QA Lead",
    department: "Engineering",
    photo: "",
  },
  {
    id: "u-2",
    fullname: "Mira Shah",
    email: "mira@acme.dev",
    role: "project_manager",
    status: "active",
    mobileNo: "+91 98765 43211",
    createdAt: "2026-05-21T09:00:00.000Z",
    designation: "Product Manager",
    department: "Product",
    photo: "",
  },
  {
    id: "u-3",
    fullname: "Dev Patel",
    email: "dev@acme.dev",
    role: "developer",
    status: "active",
    mobileNo: "+91 98765 43212",
    createdAt: "2026-06-02T09:00:00.000Z",
    designation: "Software Developer",
    department: "Engineering",
    photo: "",
  },
  {
    id: "u-4",
    fullname: "Nisha Rao",
    email: "nisha@acme.dev",
    role: "tester",
    status: "active",
    mobileNo: "+91 98765 43213",
    createdAt: "2026-06-09T09:00:00.000Z",
    designation: "QA Engineer",
    department: "Quality",
    photo: "",
  },
];

export const sampleProjects = [
  {
    id: "p-1",
    name: "Customer Portal",
    description: "Self-service dashboard for customer success teams.",
    projectUrl: "https://portal.acme.dev",
    githubUrl: "https://github.com/acme/customer-portal",
    testUrl: "https://staging.portal.acme.dev",
    techStack: "React, Node.js, MongoDB, Playwright",
    owner: "Mira Shah",
    status: "Active",
    category: "Web App",
    memberIds: ["u-1", "u-2", "u-3", "u-4"],
    bugCount: 9,
    createdAt: "2026-05-15T09:00:00.000Z",
  },
  {
    id: "p-2",
    name: "Mobile QA",
    description: "Release testing for Android and iOS builds.",
    projectUrl: "https://mobile.acme.dev",
    githubUrl: "https://github.com/acme/mobile-qa",
    testUrl: "https://staging.mobile.acme.dev",
    techStack: "React Native, Express, Supertest",
    owner: "Nisha Rao",
    status: "On Hold",
    category: "Mobile App",
    memberIds: ["u-2", "u-4"],
    bugCount: 6,
    createdAt: "2026-06-03T09:00:00.000Z",
  },
  {
    id: "p-3",
    name: "Billing Engine",
    description: "Invoice, subscription, and payment workflow service.",
    projectUrl: "https://billing.acme.dev",
    githubUrl: "https://github.com/acme/billing-engine",
    testUrl: "https://staging.billing.acme.dev",
    techStack: "Node.js, Express, MongoDB, Jest",
    owner: "Aarav Mehta",
    status: "Active",
    category: "API",
    memberIds: ["u-1", "u-3"],
    bugCount: 4,
    createdAt: "2026-06-07T09:00:00.000Z",
  },
];

export const sampleBugs = [
  {
    id: "b-1",
    ticketId: "BUG-1024",
    title: "Invoice export fails when filters are active",
    description: "CSV export returns an empty file after applying a date range filter.",
    project: "Billing Engine",
    assignedTo: "Dev Patel",
    reporter: "Mira Shah",
    status: "Open",
    priority: "Critical",
    createdAt: "2026-06-10T09:20:00.000Z",
    type: "Bug",
    screenshot: "invoice-export.png",
    comments: [
      {
        id: "c-1",
        author: "Mira Shah",
        message: "@dev customer impact is high because finance teams use this every Friday.",
        type: "comment",
        createdAt: "2026-06-10T10:05:00.000Z",
      },
    ],
    internalNotes: [
      {
        id: "n-1",
        author: "Aarav Mehta",
        message: "Keep this internal until we confirm whether the issue is backend serialization.",
        type: "note",
        createdAt: "2026-06-10T11:05:00.000Z",
      },
    ],
  },
  {
    id: "b-2",
    ticketId: "BUG-1025",
    title: "Profile avatar upload accepts oversized PNG files",
    description: "The profile form should reject screenshots and avatars above the configured limit.",
    project: "Customer Portal",
    assignedTo: "Nisha Rao",
    reporter: "Aarav Mehta",
    status: "In Progress",
    priority: "High",
    createdAt: "2026-06-11T12:15:00.000Z",
    type: "Bug",
    screenshot: "avatar-size.png",
    comments: [],
    internalNotes: [],
  },
  {
    id: "b-3",
    ticketId: "BUG-1026",
    title: "Keyboard focus is lost after status change",
    description: "Changing a bug status from the detail page resets focus to the document body.",
    project: "Customer Portal",
    assignedTo: "Dev Patel",
    reporter: "Nisha Rao",
    status: "Retest",
    priority: "Medium",
    createdAt: "2026-06-12T07:45:00.000Z",
    type: "Bug",
    screenshot: "",
    comments: [
      {
        id: "c-2",
        author: "Nisha Rao",
        message: "Verified on Chrome and Edge. Safari still needs a pass.",
        type: "comment",
        createdAt: "2026-06-13T08:00:00.000Z",
      },
    ],
    internalNotes: [],
  },
  {
    id: "b-4",
    ticketId: "BUG-1027",
    title: "Push notification toggle saves inverted value",
    description: "Disabling notifications in settings stores true in the API payload.",
    project: "Mobile QA",
    assignedTo: "Dev Patel",
    reporter: "Mira Shah",
    status: "Fixed",
    priority: "Low",
    createdAt: "2026-06-08T15:30:00.000Z",
    type: "Bug",
    screenshot: "",
    comments: [],
    internalNotes: [],
  },
  {
    id: "b-5",
    ticketId: "BUG-1028",
    title: "Search results include archived project bugs",
    description: "Archived projects are still included in the global bug search endpoint.",
    project: "Customer Portal",
    assignedTo: "Nisha Rao",
    reporter: "Aarav Mehta",
    status: "Closed",
    priority: "Medium",
    createdAt: "2026-06-06T11:10:00.000Z",
    type: "Bug",
    screenshot: "",
    comments: [],
    internalNotes: [],
  },
];
